title: GitHub/sak2212
author: Spenser
email: 
description: > # this means to ignore newlines until "baseurl:"
  learning GitHub pages

# social links
twitter_username: 
github_username:  sak2212

show_excerpts: true # set to false to remove excerpts on the homepage
